### ISSUE TITLE
"Error: Cannot find module 'paper'"

### ISSUE THREAD

**Issue by dfilan** [agentmodels/webppl-gridworld#1]
I am writing a webppl file to add to the repo, and when I try to run it with the `--require .` flag, I get this error message.

**Comment by stuhlmueller** [comment]
Did you already run `npm install` in the package directory?

**Comment by dfilan** [comment]
Oops. Am now getting: `Error: Cannot find module 'canvas'`. `npm install canvas` fails with (among other messages) `npm ERR! Failed at the canvas@1.3.9 install script 'node-gyp rebuild'.`

**Comment by stuhlmueller** [comment]
I encountered a similar issue. I found various related issues on github, including [this one](https://github.com/Automattic/node-canvas/issues/625), and resolved the problem by following the instructions there.

**Comment by dfilan** [comment]
Working now, thanks.
