### ISSUE TITLE
Running scripts from the command line

### ISSUE THREAD

**Issue by jsalvatier** [agentmodels/webppl-gridworld#16]
How do you run scripts from the command line that require webppl-timeit or dp? 

src/beliefDelayAgentTrueLatent.wppl suggests `webppl tests/testBeliefAgent.wppl --require webppl-timeit --require webppl-dp --require .`, but this doesn't seem to work. I get 

```
Processing tests/testBeliefAgent.wppl

/Users/jsalvatier/npm/lib/node_modules/webppl/src/pkg.js:64
      throw 'Could not find WebPPL package: ' + name_or_path;
      ^
Could not find WebPPL package: webppl-timeit
```

Even though I have webppl-timeit installed both locally and globally. 

Is it possible to run from the command line with the compiled js file? No right?

**Comment by stuhlmueller** [comment]
The command works for me. Did you install the packages globally using (for example) `npm install --prefix ~/.webppl webppl-timeit`?

**Comment by jsalvatier** [comment]
Yes. For me its installed in ~/npm. does the prefix matter?

**Comment by stuhlmueller** [comment]
Yes — `~/.webppl` is where webppl looks for globally installed packages.

You could also give the full (relative) path to `require`.

**Comment by jsalvatier** [comment]
Awesome, that worked.
