### ISSUE TITLE
Where is lodash coming from when running from the CLI?

### ISSUE THREAD

**Issue by jsalvatier** [agentmodels/webppl-gridworld#18]
When I run with `webppl --require webppl-timeit --require webppl-dp -require . tests/hyperbolic.sh` 

I get an error about _.get not being a function (I make this reference to _.get), but as far as I can tell lodash 4.6.1 should have _.get.

**Comment by stuhlmueller** [comment]
If you're talking about webppl code (as opposed to js code), it's using underscore (1.8.3).

**Comment by jsalvatier** [comment]
Ah, okay, that makes sense. I tried defining a function get in gridworld.js and then accessing it via GridWorld.get which also didn't work.  What am I misunderstanding?

**Comment by stuhlmueller** [comment]
Did you add it to `module.exports` in the same file?

**Comment by jsalvatier** [comment]
Yes
