### ISSUE TITLE
Watchify for incremental compilation

### ISSUE THREAD

**Issue by jsalvatier** [agentmodels/webppl-gridworld#2]
@stuhlmueller When I try `grunt watchify:../webppl-timeit:../webppl-dp:../webppl-viz:../webppl-gridworld` or `grunt watchify` in node_modules/webppl I get an error:

```
+ cd node_modules/webppl
+ grunt watchify:../webppl-timeit:../webppl-dp:../webppl-viz:../webppl-gridworld
Running "watchify:../webppl-timeit:../webppl-dp:../webppl-viz:../webppl-gridworld" (watchify) task
Fatal error: spawn watchify ENOENT
```

Any ideas what causes this?

**Comment by stuhlmueller** [comment]
Is the `watchify` command available on your system and on your `$PATH`?

**Comment by jsalvatier** [comment]
No, but I have done `npm install -g watchify`.

**Comment by jsalvatier** [comment]
I see, turned out I had not added my custom npm/bin to my path.
