### ISSUE TITLE
Trying to use compile.sh

### ISSUE THREAD

**Issue by owainevans** [agentmodels/webppl-gridworld#31]
After running install.sh, i get the following message when i run compile.sh:

erp.js is in fact not in ../webppl/src. instead it's erp.ad.js

```
Running "browserify:../webppl-timeit:../webppl-dp:../webppl-viz:/Users/owainevans/agents/webppl-gridworld" (browserify) task
Error: Cannot find module './erp' from '/Users/owainevans/agents/webppl/src'
    at /usr/local/lib/node_modules/browserify/node_modules/resolve/lib/async.js:55:21
    at load (/usr/local/lib/node_modules/browserify/node_modules/resolve/lib/async.js:69:43)
    at onex (/usr/local/lib/node_modules/browserify/node_modules/resolve/lib/async.js:92:31)
    at /usr/local/lib/node_modules/browserify/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:82:15)
Warning: Command failed: browserify -t [./src/bundle.js --require ../webppl-timeit --require ../webppl-dp --require ../webppl-viz --require /Users/owainevans/agents/webppl-gridworld] -g brfs src/browser.js -o compiled/webppl.js
Error: Cannot find module './erp' from '/Users/owainevans/agents/webppl/src'
    at /usr/local/lib/node_modules/browserify/node_modules/resolve/lib/async.js:55:21
    at load (/usr/local/lib/node_modules/browserify/node_modules/resolve/lib/async.js:69:43)
    at onex (/usr/local/lib/node_modules/browserify/node_modules/resolve/lib/async.js:92:31)
    at /usr/local/lib/node_modules/browserify/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:82:15)
 Use --force to continue.

Aborted due to warnings.
```

**Comment by jsalvatier** [comment]
Huh, weird. If you do a fresh clone of webppl-gridworld in a different directory, run install.sh then try compile.sh does the problem still happen?

**Comment by owainevans** [comment]
yeah. tried every fresh install both with and without sudo. (i have success
compiling webppl+gridworld using sudo when i compile agent models)

Owains-MacBook-Pro:webppl-gridworld owainevans$ sudo sh compile.sh
tests/hyperbolic.wppl
Running
"compile:../webppl-timeit:../webppl-dp:../webppl-viz:/Users/owainevans/gridworld-alt/webppl-gridworld"
(compile) task

Running
"browserify:../webppl-timeit:../webppl-dp:../webppl-viz:/Users/owainevans/gridworld-alt/webppl-gridworld"
(browserify) task
Error: Cannot find module './erp' from
'/Users/owainevans/gridworld-alt/webppl/src'
    at
/usr/local/lib/node_modules/browserify/node_modules/resolve/lib/async.js:55:21
    at load
(/usr/local/lib/node_modules/browserify/node_modules/resolve/lib/async.js:69:43)
    at onex
(/usr/local/lib/node_modules/browserify/node_modules/resolve/lib/async.js:92:31)
    at
/usr/local/lib/node_modules/browserify/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:82:15)
Warning: Command failed: browserify -t [./src/bundle.js --require
../webppl-timeit --require ../webppl-dp --require ../webppl-viz --require
/Users/owainevans/gridworld-alt/webppl-gridworld] -g brfs src/browser.js -o
compiled/webppl.js
Error: Cannot find module './erp' from
'/Users/owainevans/gridworld-alt/webppl/src'
    at
/usr/local/lib/node_modules/browserify/node_modules/resolve/lib/async.js:55:21
    at load
(/usr/local/lib/node_modules/browserify/node_modules/resolve/lib/async.js:69:43)
    at onex
(/usr/local/lib/node_modules/browserify/node_modules/resolve/lib/async.js:92:31)
    at
/usr/local/lib/node_modules/browserify/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:82:15)
 Use --force to continue.

Aborted due to warnings.

**Comment by owainevans** [comment]
sorry: *I tried a fresh install with ...

**Comment by jsalvatier** [comment]
can you pull in ../webppl? Or is that a totally new installation as well? I just tried doing a fresh install and had it work fine except for a syntax error in gridworld-viz.js. 

Maybe we should debug together.

**Comment by owainevans** [comment]
ok. i'm busy till later this afternoon but we can debug later if problems
persist.

try the code below. if it works, then we're probably good:
var world = makeDonutWorld2({big:true});
GridWorld.draw(world, {trajectory: [[[3, 1]]]});

if this works, please recompile webppl for agentmodels.org and push. thanks!

**Comment by jsalvatier** [comment]
The code you posted doesn't work for me (no element 0) but the following
does:

var world = makeDonutWorld2({big:true});
GridWorld.draw(world, {trajectory: [{ loc : [3, 1]}]});

I'm going to recompile.
