### ISSUE TITLE
GridWorld.draw doesn't work with state-action trajectories

### ISSUE THREAD

**Issue by dfilan** [agentmodels/webppl-gridworld#40]
The current version of GridWorld.draw seems to be fine with trajectories of state, but doesn't work with trajectories of state-action pairs.

**Comment by jsalvatier** [comment]
Can you post an example?

**Comment by dfilan** [comment]
This code doesn't work, giving the error "Cannot read property '0' of undefined":

```
var world = makeHike(0);
var startState = {loc: [0, 1]};
GridWorld.draw(world, {trajectory: [[startState, 'r']]});
```

This code works:

```
var world = makeHike(0);
var startState = {loc: [0, 1]};
GridWorld.draw(world, {trajectory: [startState]});
```
