### ISSUE TITLE
npm install fails

### ISSUE THREAD

**Issue by PropAllusion** [agentmodels/webppl-gridworld#61]
npm install --prefix ~/.webppl/ webppl-agents
npm ERR! Linux 3.16.0-4-amd64
npm ERR! argv "/usr/local/nodejs/bin/node" "/usr/local/nodejs/bin/npm" "install" "--prefix" "/home/user1/.webppl/" "webppl-agents"
npm ERR! node v7.10.0
npm ERR! npm  v4.2.0
npm ERR! code E404

npm ERR! 404 Registry returned 404 for GET on https://registry.npmjs.org/webppl-agents
npm ERR! 404 
npm ERR! 404  'webppl-agents' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

**Comment by stuhlmueller** [comment]
Try `npm install --prefix ~/.webppl/ agentmodels/webppl-agents`. The package isn't on NPM at the moment.
